import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


// Add metadata export
export const metadata: Metadata = {
  title: "AufUrlaub - Sri Lanka Travel Packages & Holiday Experiences | Reiseangebote Sri Lanka",
  description:
    "Book unforgettable Sri Lanka holidays with AufUrlaub. Explore curated travel packages, cultural tours, safaris, beaches & authentic experiences. | Buchen Sie unvergessliche Sri Lanka Reisen mit AufUrlaub – Kultur, Safari, Strände & mehr.",
  keywords: [
    "Sri Lanka travel",
    "Sri Lanka holidays",
    "Sri Lanka tour packages",
    "Sri Lanka beach vacations",
    "Sri Lanka cultural tours",
    "Sri Lanka safaris",
    "holiday packages",
    "travel agency Sri Lanka",
    "eco tours Sri Lanka",
    "luxury travel Sri Lanka",
    "Sri Lanka Reisen",
    "Sri Lanka Urlaub",
    "Sri Lanka Reiseangebote",
    "Sri Lanka Rundreisen",
    "Sri Lanka Pauschalreisen",
    "Sri Lanka Strandurlaub",
    "Sri Lanka Kulturreisen"
  ],
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
  authors: [
    { name: "AufUrlaub", url: "https://aufurlaubsrilanka.com/" },
  ],
  creator: "AufUrlaub",
  publisher: "AufUrlaub",
  icons: {
    icon: "/logo.jpg",
    shortcut: "/logo.jpg",
    apple: "/logo.jpg",
  },
  openGraph: {
    title: "AufUrlaub - Sri Lanka Travel & Holiday Packages | Sri Lanka Reisen",
    description:
      "Discover Sri Lanka with AufUrlaub. From cultural tours to safaris and beach holidays, find your perfect package. | Entdecken Sie Sri Lanka mit AufUrlaub – Kulturreisen, Safari-Abenteuer & Strandurlaub.",
    url: "https://aufurlaubsrilanka.com/",
    siteName: "AufUrlaub",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "AufUrlaub - Sri Lanka Travel Packages | Sri Lanka Reisen",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AufUrlaub - Sri Lanka Travel Packages | Sri Lanka Reisen",
    description:
      "Plan your dream Sri Lanka holiday with AufUrlaub. Explore beaches, safaris, culture & eco tours. | Planen Sie Ihren Traumurlaub in Sri Lanka mit AufUrlaub – Strände, Safari, Kultur & Ökotourismus.",
    images: ["/og-image.jpg"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
