import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


// Add metadata export
export const metadata: Metadata = {
  title: "Sri Lanka Urlaub – Rundreisen, Kultur & Traumstrände erleben",
  description:
    "Planen Sie Ihren Traumurlaub mit Urlaub auf Sri Lanka. Genießen Sie maßgeschneiderte Touren, atemberaubende Natur, historische Tempel und paradiesische Strände.",
  keywords: [
  "Sri Lanka Urlaub",
  "Sri Lanka Rundreisen",
  "Sri Lanka Urlaub buchen",
  "Beste Reisezeit Sri Lanka Urlaub",
  "Sri Lanka Rundreise Anbieter",
  "Sri Lanka Individualreise"
],
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
  authors: [
    { name: "AufUrlaub", url: "https://aufurlaubsrilanka.com/" },
  ],
  creator: "AufUrlaub",
  publisher: "AufUrlaub",
  icons: {
    icon: "/logo.jpg",
    shortcut: "/logo.jpg",
    apple: "/logo.jpg",
  },
  openGraph: {
    title: "Sri Lanka Urlaub – Rundreisen, Kultur & Traumstrände erleben",
    description:
      "Planen Sie Ihren Traumurlaub mit Urlaub auf Sri Lanka. Genießen Sie maßgeschneiderte Touren, atemberaubende Natur, historische Tempel und paradiesische Strände.",
    url: "https://aufurlaubsrilanka.com/",
    siteName: "Auf Urlaub Sri Lanka",
    images: [
      {
        url: "/headImage/img_4.webp",
        width: 630,
        height: 630,
        alt: "Sri Lanka Urlaub – Rundreisen, Kultur & Traumstrände erleben",
      },
    ],
   locale: "de_DE",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Sri Lanka Urlaub – Rundreisen, Kultur & Traumstrände erleben",
    description:
      "Planen Sie Ihren Traumurlaub mit Urlaub auf Sri Lanka. Genießen Sie maßgeschneiderte Touren, atemberaubende Natur, historische Tempel und paradiesische Strände.",
    images: ["/headImage/img_4.webp"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
